class Burnmail < Formula
  desc "Simple CLI tool to generate and manage temporary email addresses with TUI"
  homepage "https://github.com/fraluc06/burnmail"
  url "https://github.com/fraluc06/burnmail/archive/refs/tags/v2.0.0.tar.gz"
  sha256 "5a25f28bc876a7d5be8c4b49c2debf98dbaef909e2ffb9d11e98b7503773e528"
  license "MIT"
  head "https://github.com/fraluc06/burnmail.git", branch: "main"

  livecheck do
    url :stable
    :github_latest
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X burnmail/internal/config.Version=#{version}")

    # burnmail defines its own `completion` command accepting only
    # bash|zsh|fish (cobra's :cobra default would also request pwsh).
    generate_completions_from_executable(bin/"burnmail", shell_parameter_format: :cobra, shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/burnmail --version")

    # The completions are generated by the binary during install (running
    # the real cobra tree, offline): their presence proves the command
    # wiring works, and the bash one also guarantees burnmail's functions.
    bash = etc/"bash_completion.d/burnmail"
    assert_path_exists bash
    assert_path_exists share/"zsh/site-functions/_burnmail"
    assert_path_exists share/"fish/vendor_completions.d/burnmail.fish"
    assert_match "__burnmail", bash.read
  end
end
