name: Release Formulae (Livecheck)

on:
  release:
    types: [ released ]

  workflow_dispatch:
    inputs:
      formula:
        description: 'Formula to release (leave empty to check all)'
        required: false
        default: ''
  schedule:
    - cron: '0 5 1 * *'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump:
    name: Bump formulae
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push commits
    steps:
      - name: Trust tap
        run: |
          mkdir -p ~/.homebrew ~/.config/homebrew
          echo '{"trustedtaps":["fraluc06/homebrew-tap","fraluc06/tap"]}' > ~/.homebrew/trust.json
          echo '{"trustedtaps":["fraluc06/homebrew-tap","fraluc06/tap"]}' > ~/.config/homebrew/trust.json

      - name: Update formulae using Livecheck
        uses: dawidd6/action-homebrew-bump-formula@a0e064e08103c01870c6d1b05168d1b726aab119 # v8
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          tap: fraluc06/homebrew-tap
          formula: ${{ inputs.formula }}
          livecheck: true
