name: Release Casks (Livecheck)

on:
  release:
    types: [ released ]

  workflow_dispatch:
    inputs:
      cask:
        description: 'Cask to release (leave empty to check all)'
        required: false
        default: ''
  schedule:
    - cron: '0 5 1 * *'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump:
    name: Bump casks
    runs-on: macos-26
    permissions:
      contents: write # to push commits
    steps:
      - name: Trust tap
        run: |
          mkdir -p ~/.homebrew ~/.config/homebrew
          echo '{"trustedtaps":["fraluc06/homebrew-tap","fraluc06/tap"]}' > ~/.homebrew/trust.json
          echo '{"trustedtaps":["fraluc06/homebrew-tap","fraluc06/tap"]}' > ~/.config/homebrew/trust.json

      - name: Update casks using Livecheck
        uses: friesi23/action-homebrew-bump-cask@561bbe447f8915a50a62e65483061bea1e7f136f # v2.0
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          tap: fraluc06/homebrew-tap
          cask: ${{ inputs.cask }}
          livecheck: true
